sudo: false

os:
  - linux

language: d

d:
  - ldc
  - dmd

env:
  - ARCH="x86_64"

matrix:
  include:
    - {os: linux, d: ldc, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib, libcurl4-gnutls-dev]]}}}
    - {os: linux, d: dmd, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib, libcurl4-gnutls-dev]]}}}

before_install:
  - if [ $ARCH = "x86_64" ]; then
      wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz;
      tar xvf ffmpeg-git-64bit-static.tar.xz;
    else
      wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-32bit-static.tar.xz;
      tar xvf ffmpeg-git-32bit-static.tar.xz;
    fi
  - cd ffmpeg-git*/ && export PATH=`pwd`:$PATH && cd -

script:
  - wget https://raw.githubusercontent.com/ShigekiKarita/torch-nmf-ss-toy/master/test10k.wav
  - dub test --arch "$ARCH" --build=unittest-cov
  - if [ $DC = dmd ] && [ $ARCH = "x86_64" ]; then
      dub build -b=docs --compiler=dmd;
      mv docs/dffmpeg.html docs/index.html;
      touch docs/.nojekyll;
    fi

after_success:
 - bash <(curl -s https://codecov.io/bash)

deploy:
  d: dmd
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
    condition: $DC = dmd && $ARCH = "x86_64"
